www/log_manage/urls.py
# coding=utf8
from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy
from log_manage.views import (HitListDetailView, RuleStrategyMapView,
                              AuditLogListView)

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy("log_manage:hit_list_detail"),
                             permanent=True), name="log_manage_index"),

    url(r'^hit/list_detail/$', HitListDetailView.as_view(),
        name="hit_list_detail"),
    url(r'^rule_strategy_map/$', RuleStrategyMapView.as_view(),
        name="rule_strategy_map"),
    url(r'^audit_log_list/$', AuditLogListView.as_view(), name='audit_logs')
]

www/menu/urls.py
# coding=utf8
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from menu.views import (UseridListView, MenuCreateView, MenuDestroyView, IpListView,
                        UidListView, PayListView, PhoneListView,
                        EventListView, EventCreateView, EventDestroyView)

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy("menus:event_list"), permanent=True), name="menu_index"),

    url(r'^common_create/$', MenuCreateView.as_view(), name="create"),
    url(r'^common_delete/$', MenuDestroyView.as_view(), name="delete"),

    url(r'^event/list/$', EventListView.as_view(), name="event_list"),
    url(r'^event/create/$', EventCreateView.as_view(), name="event_create"),
    url(r'^event/destroy/$', EventDestroyView.as_view(), name="event_destroy"),

    url(r'^userid/list/$', UseridListView.as_view(), name="userid_list"),
    url(r'^ip/list/$', IpListView.as_view(), name="ip_list"),
    url(r'^uid/list/$', UidListView.as_view(), name="uid_list"),
    url(r'^pay/list/$', PayListView.as_view(), name="pay_list"),
    url(r'^phone/list/$', PhoneListView.as_view(), name="phone_list"),
]

www/risk_auth/urls.py
# coding=utf8

from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.contrib.auth.decorators import login_required

from risk_auth.views import Home
from risk_auth.views import risk_login, risk_logout

urlpatterns = [
    url(r'^$', login_required(Home.as_view()), name='home'),
    url(r'^home/$', RedirectView.as_view(url=reverse_lazy('risk_auth:home'), permanent=True)),
    url(r'^accounts/login/$', risk_login, name="risk_login"),
    url(r'^accounts/logout/$', risk_logout, name="risk_logout"),
]

www/strategy/urls.py
# coding=utf8

from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from strategy.views import (
    BoolStrategyListView, BoolStrategyCreateView, BoolStrategyDestroyView,
    BoolStrategyTestView, BoolStrategyDataView,
    FreqStrategyListView, FreqStrategyCreateView, FreqStrategyDestroyView,
    FreqStrategyTestView, FreqStrategyDataView,
    MenuStrategyListView, MenuStrategyCreateView, MenuStrategyDestroyView,
    MenuStrategyTestView, MenuStrategyDataView,
    UserStrategyListView, UserStrategyCreateView, UserStrategyDestroyView,
    UserStrategyTestView, UserStrategyDataView,
)

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy("strategy:strategy_list"),
                             permanent=True), name="strategy_index"),
    # 名单型策略
    url(r'^menu_strategy/list/$', MenuStrategyListView.as_view(),
        name="menu_strategy_list"),
    url(r'^menu_strategy/create/$', MenuStrategyCreateView.as_view(),
        name="menu_strategy_create"),
    url(r'^menu_strategy/destroy/$', MenuStrategyDestroyView.as_view(),
        name="menu_strategy_destroy"),
    url(r'^menu_strategy/test/$', MenuStrategyTestView.as_view(),
        name="menu_strategy_test"),
    url(r'^menu_strategy/data/$', MenuStrategyDataView.as_view(),
        name="menu_strategy_data"),

    # 布尔型策略
    url(r'^bool_strategy/list/$', BoolStrategyListView.as_view(),
        name="bool_strategy_list"),
    url(r'^bool_strategy/create/$', BoolStrategyCreateView.as_view(),
        name="bool_strategy_create"),
    url(r'^bool_strategy/destroy/$', BoolStrategyDestroyView.as_view(),
        name="bool_strategy_destroy"),
    url(r'^bool_strategy/test/$', BoolStrategyTestView.as_view(),
        name="bool_strategy_test"),
    url(r'^bool_strategy/data/$', BoolStrategyDataView.as_view(),
        name="bool_strategy_data"),

    # 时段频控策略
    url(r'^freq_strategy/list/$', FreqStrategyListView.as_view(),
        name="freq_strategy_list"),
    url(r'^freq_strategy/create/$', FreqStrategyCreateView.as_view(),
        name="freq_strategy_create"),
    url(r'^freq_strategy/destroy/$', FreqStrategyDestroyView.as_view(),
        name="freq_strategy_destroy"),
    url(r'^freq_strategy/test/$', FreqStrategyTestView.as_view(),
        name="freq_strategy_test"),
    url(r'^freq_strategy/data/$', FreqStrategyDataView.as_view(),
        name="freq_strategy_data"),

    # 限用户数型策略
    url(r'^user_strategy/list/$', UserStrategyListView.as_view(),
        name="user_strategy_list"),
    url(r'^user_strategy/create/$', UserStrategyCreateView.as_view(),
        name="user_strategy_create"),
    url(r'^user_strategy/destroy/$', UserStrategyDestroyView.as_view(),
        name="user_strategy_destroy"),
    url(r'^user_strategy/test/$', UserStrategyTestView.as_view(),
        name="user_strategy_test"),
    url(r'^user_strategy/data/$', UserStrategyDataView.as_view(),
        name="user_strategy_data"),
]

www/urls.py
# coding=utf8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include("risk_auth.urls", namespace='risk_auth')),
    url(r'permissions/', include("permissions.urls", namespace="permissions")),
    url(r'strategy/', include("strategy.urls", namespace="strategy")),
    url(r'menu/', include("menu.urls", namespace="menus")),
    url(r'rule/', include("rule.urls", namespace="rule")),
    url(r'config/', include("bk_config.urls", namespace="config")),
    url(r'log_manage/', include("log_manage.urls", namespace="log_manage")),
]

# 用于线上时应移除此部分，动静分离
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    from django.views.defaults import (page_not_found, server_error,
                                       permission_denied)

    urlpatterns += [
        url(r'404/', page_not_found),
        url(r'500/', server_error),
        url(r'403/', permission_denied),
    ]

www/templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

{% url 'permissions:index' as permissions_index %}
{% url 'permissions:users' as permissions_users %}
{% url 'permissions:groups' as permissions_groups %}
{% url 'permissions:uri_groups' as permissions_uri_groups %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="renderer" content="webkit">

    <title>风控管理</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <script src="{% static 'js/vendor/jquery.min.js' %}"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'widget/datetimepicker/bootstrap-datetimepicker.css' %}" rel="stylesheet">
    <link href="{% static 'widget/datetimepicker/datetimepicker.css' %}" rel="stylesheet">
    {% block css %}{% endblock %}
    <link href="{% static 'css/multi-select.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">
    <link href="{% static 'css/filter-form.css' %}" rel="stylesheet">
    <link href="{% static 'css/pagination.css' %}" rel="stylesheet">
    <link href="{% static 'css/plugins/sweetalert/sweetalert.css' %}" rel="stylesheet">
    <link href="{% static 'css/jquery.searchableSelect.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}?v=3" rel="stylesheet">
</head>

<body class="fixed-sidebar full-height-layout extra-main-bg" style="overflow:hidden">
<div id="wrapper">
    <!--侧边栏-->
    {% include 'siderbar.html' %}

    <div id="extra-main-page" class="extra-main-bg">
        <nav class="navbar navbar-default extra-navbar-default">
            <div class="container-fluid">
                <div class="row extra-nav">
                    <div class="col-md-8 extra-tab-title">
                        {% block header %}
                        <a>风控管理中心</a>
                        {% endblock %}
                    </div>
                    <div class="col-md-4">
                        {% block action %}{% endblock %}
                    </div>
                </div>
            </div>
        </nav>

        {% block content %}
        <div class="row" id="content-main">
            {% block main %} {% endblock %}
        </div>
        {% endblock %}
    </div>
</div>

<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/csrf.js' %}"></script>
<script src="{% static 'js/content.min.js' %}"></script>
<script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
<script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.min.js' %}"></script>
<script src="{% static 'js/plugins/sweetalert/sweetalert.min.js' %}"></script>

<script src="{% static 'js/jquery-ui-1.10.4.min.js' %}"></script>
<script src="{% static 'js/jquery.searchableSelect.js' %}"></script>
<script src="{% static 'js/jquery.multi-select.js' %}"></script>
<script src="{% static 'js/jquery.quicksearch.js' %}"></script>
<script src="{% static 'widget/datetimepicker/bootstrap-datetimepicker.js' %}"></script>
<script src="{% static 'js/default_time.js' %}"></script>

<!--Custom JS-->
<script src="{% static 'js/uri_scene.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block js %}{% endblock %}

</body>
</html>

www/templates/datepicker.html
{% load i18n %}
{% load staticfiles %}


{% block js %}
<script>
    jQuery(function () {
        $(".date").datetimepicker({
            format: 'yyyy-mm-dd',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 2
        });

        $(".datetime, .datetimeinput").datetimepicker({
            format: 'yyyy-mm-dd hh:ii',
            weekStart: 1,
            todayBtn: 1,
            autoclose: 1,
            todayHighlight: 1,
            startView: 2,
            minView: 0
        });
    })
</script>
{% endblock %}

www/templates/error_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-hans">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>风控管理 - {% block error_code %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/main.css" rel="stylesheet">
</head>
<body class="extra-main-bg">
    <div class="extra-error-page-content">
        <h1>{% block error_code_title %}200{% endblock %}</h1>
        <h3 class="font-bold">{% block error_code_title_zh %}空白页面{% endblock %}</h3>
        <div class="extra-error-desc">{% block error_code_desc %}这一个空白页面{% endblock %}</div>
        <a href="/" class="btn btn-primary m-t">主页</a>
    </div>
</body>
</html>

www/templates/pagination.html
{% load i18n %}
{% load django_tables2 %}

{% trans '共查询出' %}{{ record_count }}{% trans '条数据' %}

{% if is_paginated %}
    {% if enable_page_size_config %}
        <style type="text/css">
            .count-container {
                text-align: right;
                padding-top: 15px;
            }
            .count-container select {
                width: 50px;
            }
        </style>
        <div class="count-container">
            {% trans '每页显示' %}
            <select name="count" id="change-count">
            {% for value in page_values %}
                <option  value="{{ value }}" {% if value == page_size %} selected {% endif %}>{{ value }}</option>
            {% endfor %}
            </select>
            {% trans '条数据' %}
        </div>
        <script type="text/javascript">
            function getUrlVars() {
                var vars = {};
                if (window.location.href.indexOf('?') > 0) {
                    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
                    for (var i = 0; i < hashes.length; i++) {
                        hash = hashes[i].split('=');
                        vars[hash[0]] = hash[1];
                    }
                }
                return vars;
            }
            $("body").on("change", "#change-count", function () {
                var value = $(this).val();
                var urlVars = getUrlVars(window.location.href);
                urlVars['page_size'] = value;
                urlVars['page'] = 1;
                var itemArray = [];
                $.each(urlVars, function (key, value) {
                    if (value) {
                       itemArray.push(key + '=' + value);
                   }
                });
                var path = itemArray.join("&");

                window.location.href = window.location.origin + window.location.pathname + "?" + path;
            });
        </script>
    {% endif %}

    <div class="pagination">
        <div class="goto" id="goto">
            <input type="text" value="" class="num"/>
            <a href="" data-href="{% querystring table.prefixed_page_field='' %}">{% trans '跳页 ' %}</a>
        </div>

        <div class="page-show">
            {% block pagination.previous %}
                {% if page_obj.has_previous %}
                    <a href="{% querystring table.prefixed_page_field=page_obj.previous_page_number %}" class="prev">{{ previous_link_decorator|safe }}上一页</a>
                {% endif %}
            {% endblock pagination.previous %}

            {% block pagination.cardinality %}
                {% for page in pages %}
                    {% if page %}
                        {% ifequal page page_obj.number %}
                            <span class="current page">{{ page }}</span>
                        {% else %}
                            <a href="{% querystring table.prefixed_page_field=page %}" class="page">{{ page }}</a>
                        {% endifequal %}
                    {% else %}
                        ...
                    {% endif %}
                {% endfor %}
            {% endblock pagination.cardinality %}

            {% block pagination.next %}
                {% if page_obj.has_next %}
                    <a href="{% querystring table.prefixed_page_field=page_obj.next_page_number %}" class="next">{% trans '下一页' %}{{ next_link_decorator|safe }}</a>
                {% endif %}
            {% endblock pagination.next %}
        </div>
    </div>

    <script>
        "use strict";

        var _oGo = $('#goto'),
            _inpNum = _oGo.find('input'),
            _btnConfirm = _oGo.find('a');

        $(".num").on("keyup", function() {

            var pageNum = $(this).val(),
                maxNum = parseFloat($(".page-show .page").eq(-1).text()),
                reg = /^\d*$/;

            if(!reg.test(pageNum)) {
                $(this).val("");
            } else {
                pageNum = parseFloat(pageNum);

                if (pageNum > maxNum){
                    $(this).val(maxNum);
                }
                if(pageNum <= 0){
                    $(this).val("1");
                }
            }
        });

        _btnConfirm.on("click", function() {

            var pageNum = $.trim(_inpNum.val());
            var hrefPrefix = _btnConfirm.attr('data-href');
            hrefPrefix = hrefPrefix.replace("&submit=%E6%9F%A5%E8%AF%A2", "");

            if(pageNum == "") {
                return false;
            } else {

                _btnConfirm[0].href = hrefPrefix + pageNum;
            }
        });
    </script>
{% endif %}

www/templates/siderbar.html
{% load staticfiles %}

{% url 'home' as home_page %}

{% url 'permissions:index' as permissions_index %}
{% url 'permissions:users' as permissions_users %}
{% url 'permissions:groups' as permissions_groups %}
{% url 'permissions:uri_groups' as permissions_uri_groups %}

{% url 'strategy:menu_strategy_list' as menu_strategy_url %}
{% url 'strategy:bool_strategy_list' as bool_strategy_url %}
{% url 'strategy:freq_strategy_list' as freq_strategy_url %}
{% url 'strategy:user_strategy_list' as user_strategy_url %}

{% url 'rule:list' as rule_list_url %}

{% url 'menus:event_list' as menu_event_list %}
{% url 'menus:userid_list' as menu_userid_list %}
{% url 'menus:uid_list' as menu_uid_list %}
{% url 'menus:ip_list' as menu_ip_list %}
{% url 'menus:pay_list' as menu_pay_list %}
{% url 'menus:phone_list' as menu_phone_list %}

{% url 'competition:competition_list' as competition_list_url %}

{% url 'config:source_list' as source_list %}
{% url 'config:upload_source_list' as upload_source_list %}
{% url 'config:ordering_business_list' as ordering_business_list %}

{% url 'log_manage:hit_list_detail' as hit_list_detail %}
{% url 'log_manage:audit_logs' as audit_logs %}

<style>
    i {
        width: 10px;
        text-align: right;
    }
</style>

<nav class="navbar-default extra-navbar-right" role="navigation">
    <div>
        <i class="fa fa-times-circle"></i>
    </div>
    <div class="">
        <ul class="nav" id="extra-side-menu">
            <li class="nav-header">
                    <span >
                        <a href="{{ home_page }}"><center><img alt="image" height="64px" width="175px" src="{% static 'img/icon.png' %}"/></center>
                        <center><h3>风控系统</h3></center></a>
                    </span>
                    <br>
                    <span>
                        <a>
                            <i class="fa fa-circle extra-online-icon"></i>
                            <strong>{{ request.user.last_name }}{{ request.user.first_name }}</strong>
                        </a>
                    </span>
                    <span>
                    <a href="{% url 'risk_auth:risk_logout' %}" style="margin-left: 10px">
                         退出
                    </a>
                    </span>
            </li>

            <li class="siderbar">
                <a href="#">
                    <span class="nav-label">名单管理</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav extra-nav-level-2">
                    {% if menu_event_list in project_perms %}
                    <li class="siderbar">
                        <a href="{{ menu_event_list }}">名单项目管理</a>
                    </li>
                    {% endif %}
                    {% if menu_userid_list in project_perms %}
                    <li class="siderbar">
                        <a href="{{ menu_userid_list }}">用户ID管理</a>
                    </li>
                    {% endif %}
                    {% if menu_ip_list in project_perms %}
                    <li class="siderbar">
                        <a href="{{ menu_ip_list }}">IP地址管理</a>
                    </li>
                    {% endif %}
                    {% if menu_uid_list in project_perms %}
                    <li class="siderbar">
                        <a href="{{ menu_uid_list }}">设备号管理</a>
                    </li>
                    {% endif %}
                    {% if menu_pay_list in project_perms %}
                    <li class="siderbar">
                        <a href="{{ menu_pay_list }}">支付账号管理</a>
                    </li>
                    {% endif %}
                    {% if menu_phone_list in project_perms %}
                    <li class="siderbar">
                        <a href="{{ menu_phone_list }}">手机号管理</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            <li class="siderbar">
                <a href="#">
                    <span class="nav-label">策略原子管理</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav extra-nav-level-2">

                    {% if menu_strategy_url in project_perms %}
                    <li class="siderbar">
                        <a href="{{ menu_strategy_url }}">名单型策略配置</a>
                    </li>
                    {% endif %}
                    {% if bool_strategy_url in project_perms %}
                    <li class="siderbar">
                        <a href="{{ bool_strategy_url }}">布尔型策略配置</a>
                    </li>
                    {% endif %}
                    {% if freq_strategy_url in project_perms %}
                    <li class="siderbar">
                        <a href="{{ freq_strategy_url }}">时段频控型策略配置</a>
                    </li>
                    {% endif %}
                    {% if user_strategy_url in project_perms %}
                    <li class="siderbar">
                        <a href="{{ user_strategy_url }}">限用户数型策略配置</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            <li class="siderbar">
                <a href="#">
                    <span class="nav-label">规则管理</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav extra-nav-level-2">
                    {% if rule_list_url in project_perms %}
                    <li class="siderbar">
                        <a href="{{ rule_list_url }}">规则配置</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            <li class="siderbar">
                <a href="#">
                    <span class="nav-label">日志管理</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav extra-nav-level-2">
                    {% if hit_list_detail in project_perms %}
                    <li class="siderbar">
                        <a href="{{ hit_list_detail }}">拦截日志详情</a>
                    </li>
                    {% endif %}
                    {% if audit_logs in project_perms %}
                    <li class="siderbar">
                        <a href="{{ audit_logs }}">访问日志详情</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            <li class="siderbar">
                <a href="#">
                    <span class="nav-label">权限管理</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav extra-nav-level-2">
                    {% if permissions_users in project_perms %}
                    <li class="siderbar">
                        <a href="{{ permissions_users }}">用户</a>
                    </li>
                    {% endif %}
                    {% if permissions_groups in project_perms %}
                    <li class="siderbar">
                        <a href="{{ permissions_groups }}">组</a>
                    </li>
                    {% endif %}
                    {% if permissions_uri_groups in project_perms %}
                    <li class="siderbar">
                        <a href="{{ permissions_uri_groups }}">权限</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
            <li class="siderbar">
                <a href="#">
                    <span class="nav-label">后台配置</span>
                    <span class="fa arrow"></span>
                </a>
                <ul class="nav extra-nav-level-2">
                    {% if source_list in project_perms %}
                    <li class="siderbar">
                        <a href="{{ source_list }}">数据源配置</a>
                    </li>
                    {% endif %}
                </ul>
            </li>
        </ul>
    </div>
</nav>

<script>
    $(function () {
        // 动作菜单 -- 导航菜单 对应关系
        var actionPages = {
            '/permissions/user/update/': "/permissions/users/",
            '/permissions/group/create/':"/permissions/groups/",
            '/permissions/group/update/':"/permissions/groups/",
            '/permissions/uri_group/create/':"/permissions/uri_groups/",
            '/permissions/uri_group/update/':"/permissions/uri_groups/",

            '/rules/menu/create/': "/rules/menu/list/",

            '/strategy/bool_strategy/test/': "/strategy/bool_strategy/list/",
            '/strategy/bool_strategy/create/': "/strategy/bool_strategy/list/",

            '/strategy/freq_strategy/create/': "/strategy/freq_strategy/list/",
            '/strategy/freq_strategy/test/': "/strategy/freq_strategy/list/",

            '/strategy/user_strategy/create/': "/strategy/user_strategy/list/",
            '/strategy/user_strategy/test/': "/strategy/user_strategy/list/",

            '/strategy/menu_strategy/create/': "/strategy/menu_strategy/list/",
            '/strategy/menu_strategy/test/': "/strategy/menu_strategy/list/",

            '/rule/create/': "/rule/list/",
            '/rule/detail/': "/rule/list/",
            '/rule/edit/': "/rule/list/",
            '/rule/test/': "/rule/list/",
        };
        // 定义当前导航菜单
        var currentPath = actionPages[window.location.pathname] ? actionPages[window.location.pathname] : window.location.pathname;
        // 选择当前导航a标签
        var selector = 'a[href="' + currentPath + '"]';
        var currentNav = $(selector);
        // 控制父级菜单高亮
        currentNav.parents('li.siderbar').addClass('active');
        // 控制父级菜单展开
        currentNav.parents('ul.nav').addClass('collapse in');

        // 控制无子菜单的一二级菜单的显隐
        $("ul:not(:has(li))").parent().addClass('hide');
    });

</script>

www/templates/table.html
{% extends "django_tables2/table.html" %}


{% load i18n %}
{% load django_tables2 %}


{% block table.thead %}
    <thead>
        <tr>
        {% for column in table.columns %}
            {% if column.orderable %}
            <th {{ column.attrs.th.as_html }}>
                <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">
                    <span class="fn">{{ column.header }}</span>
                </a>
            </th>
            {% else %}
            <th {{ column.attrs.th.as_html }}>{{ column.header }}</th>
            {% endif %}
        {% endfor %}
        </tr>
    </thead>
{% endblock table.thead %}


{% block table.tbody.empty_text %}
    <tr><td class="tfoot-empty txt-center" colspan="{{ table.columns|length }}">{{ table.empty_text|safe }}</td></tr>
{% endblock table.tbody.empty_text %}


{% block table.tfoot %}
    {% if table.deletable and table.page.object_list %}
    <tfoot class="check-tfoot">
        <tr>
            <td colspan="{{ table.columns|length }}">
                <input type="checkbox" id="checkall-bottom" class="check-all" name="checkall" />
                <label for="checkall-bottom">{% trans "全选" %}</label>
                <a id="batchDelete" class="btn btn-primary" style="padding: 4px 8px;" data-uri="{{ batch_delete_uri }}">{% trans "删除" %}</a>
            </td>
        </tr>
    </tfoot>
    {% endif %}
    {% if table.editable and table.page.object_list %}
    <tfoot class="check-tfoot">
        <tr>
            <td colspan="{{ table.columns|length }}">
                <input type="checkbox" id="checkall-bottom" class="check-all" name="checkall" />
                <label for="checkall-bottom">{% trans "全选" %}</label>
                <a id="batchEdit" class="btn btn-primary" style="padding: 4px 8px;">{% trans "批量编辑" %}</a>
                <a id="batchEditSave" class="btn btn-primary" disabled="disabled" style="padding: 4px 8px;" data-uri="{{ batch_edit_uri }}">{% trans "保存" %}</a>
            </td>
        </tr>
    </tfoot>
    {% endif %}
{% endblock table.tfoot %}


{% block pagination %}
    {% include "pagination.html" %}
{% endblock %}