www/menu/urls.py
# coding=utf8
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from menu.views import (UseridListView, MenuCreateView, MenuDestroyView, IpListView,
                        UidListView, PayListView, PhoneListView,
                        EventListView, EventCreateView, EventDestroyView)

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy("menus:event_list"), permanent=True), name="menu_index"),

    url(r'^common_create/$', MenuCreateView.as_view(), name="create"),
    url(r'^common_delete/$', MenuDestroyView.as_view(), name="delete"),

    url(r'^event/list/$', EventListView.as_view(), name="event_list"),
    url(r'^event/create/$', EventCreateView.as_view(), name="event_create"),
    url(r'^event/destroy/$', EventDestroyView.as_view(), name="event_destroy"),

    url(r'^userid/list/$', UseridListView.as_view(), name="userid_list"),
    url(r'^ip/list/$', IpListView.as_view(), name="ip_list"),
    url(r'^uid/list/$', UidListView.as_view(), name="uid_list"),
    url(r'^pay/list/$', PayListView.as_view(), name="pay_list"),
    url(r'^phone/list/$', PhoneListView.as_view(), name="phone_list"),
]

www/urls.py
# coding=utf8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include("risk_auth.urls", namespace='risk_auth')),
    url(r'permissions/', include("permissions.urls", namespace="permissions")),
    url(r'strategy/', include("strategy.urls", namespace="strategy")),
    url(r'menu/', include("menu.urls", namespace="menus")),
    url(r'rule/', include("rule.urls", namespace="rule")),
    url(r'config/', include("bk_config.urls", namespace="config")),
    url(r'log_manage/', include("log_manage.urls", namespace="log_manage")),
]

# 用于线上时应移除此部分，动静分离
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    from django.views.defaults import (page_not_found, server_error,
                                       permission_denied)

    urlpatterns += [
        url(r'404/', page_not_found),
        url(r'500/', server_error),
        url(r'403/', permission_denied),
    ]

www/menu/forms.py
# coding=utf8
import re
import json
import uuid
import datetime

from django import forms
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from core.pymongo_client import get_mongo_client
from core.forms import BaseFilterForm, BaseForm
from core.redis_client import get_redis_client
from risk_models.menu import build_redis_key

# 查询时有全部名单
MENU_TYPE_CHOICES = (
    (u'', u'全部名单'),
    (u'black', u'黑名单'),
    (u'white', u'白名单'),
    (u'gray', u'灰名单')
)

MENU_STATUS_CHOICES = (
    (u'有效', u'有效'),
    (u'全部', u'全部'),
    (u'无效', u'无效')
)

# 新增时没有全部名单
MENU_TYPE_CHOICES_ADD_CHOICES = MENU_TYPE_CHOICES[1:]

MENU_TYPE_NAME_MAP = dict(MENU_TYPE_CHOICES_ADD_CHOICES)

DIMENSION_NAME_MAP = {
    "user_id": u"用户ID",
    "ip": u'IP地址',
    "phone": u"手机号",
    "uid": u"设备号",
    "pay": u"支付账号"
}


class MenuEventCreateForm(BaseForm):
    event_name = forms.CharField()

    def clean_event_name(self):
        db = get_mongo_client()
        event_name = self.cleaned_data['event_name'].strip()
        res = db.menu_event.find_one({'event_name': event_name})
        if res:
            raise forms.ValidationError(u"该项目名称已存在")
        return event_name

    def save(self, *args, **kwargs):
        db = get_mongo_client()
        cd = self.cleaned_data
        event_code = str(uuid.uuid4())
        pay_load = dict(
            event_code=event_code,
            event_name=cd['event_name']
        )
        db.menu_event.insert_one(pay_load)
        return event_code


class MenuCreateForm(BaseForm):
    value = forms.CharField(widget=forms.Textarea(
        attrs={"placeholder": "用户ID[批量添加时请以回车键隔开]", "rows": "5"}))
    dimension = forms.CharField(required=False, widget=forms.HiddenInput,
                                label=_(u'名单维度'))
    menu_type = forms.ChoiceField(label=_(u"名单类型"),
                                  choices=MENU_TYPE_CHOICES_ADD_CHOICES)
    event_code = forms.ChoiceField(label=_(u"项目"))
    end_time = forms.DateTimeField(widget=forms.TextInput(
        attrs={"placeholder": "结束时间", "class": "form-control datetime"}))
    menu_desc = forms.CharField(required=False, widget=forms.Textarea(
        attrs={"placeholder": "备注[填写增加该批数据的原因]", "rows": "5"}))

    def __init__(self, *args, **kwargs):
        super(MenuCreateForm, self).__init__(*args, **kwargs)
        self.fields['event_code'].choices = self._build_event_choices()

    @classmethod
    def _build_event_choices(cls):
        db = get_mongo_client()
        choices = [(x["event_code"], x["event_name"]) for x in
                   db['menu_event'].find({}, projection={'_id': False,
                                                         'event_code': True,
                                                         'event_name': True})]
        return choices

    def clean_value(self):
        value = self.cleaned_data['value']
        value_list = list(set(value.split()))
        try:
            json.dumps(value_list)
        except ValueError:
            raise forms.ValidationError(u"输入非法")
        if not value_list:
            raise forms.ValidationError(u"该字段是必填项。")
        return value_list

    def clean_end_time(self):
        end_time = self.cleaned_data['end_time']
        if end_time <= timezone.now():
            raise forms.ValidationError(_(u"结束时间应大于当前时间"))
        return end_time

    def _check_regex(self, values, regex):
        errors = []
        for item in values:
            if not re.match(regex, item):
                errors.append(item)
        if errors:
            msg = ', '.join(errors)
            msg = u'输入非法: {}'.format(msg)
            self.errors['value'] = [msg]

    def clean(self):
        cd = self.cleaned_data
        dimension = cd['dimension']
        values = cd['value']

        if dimension == "phone":
            self._check_regex(values, r'^1\d{10}$')
        elif dimension == 'ip':
            self._check_regex(
                values,
                r'^((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)$'
            )
        return cd

    def save(self, *args, **kwargs):
        """新增时，若存在维度值+项目+名单类型相同情况，则update为新增值"""
        cd = self.cleaned_data
        value_list = cd['value']
        chinese_name = self.request.user.username
        error_datas = []
        end_time = cd['end_time'].replace(tzinfo=None)

        db = get_mongo_client()
        redis_client = get_redis_client()
        for value in value_list:
            payload = dict(
                end_time=end_time,
                menu_desc=cd['menu_desc'],
                menu_status=u"有效",
                create_time=datetime.datetime.now(),
                creator=chinese_name
            )

            value = value.strip()
            dimension = cd['dimension']
            menu_type = cd['menu_type']
            event_code = cd.get('event_code')

            condition = dict(value=value,
                             event_code=event_code,
                             menu_type=menu_type,
                             dimension=dimension
                             )
            res = db.menus.find_one(condition)

            try:
                if not res:
                    payload.update(condition)
                    db.menus.insert_one(payload)
                else:
                    db.menus.update_one({"_id": res.get("_id", '')},
                                        {"$set": payload})

                #  同时写redis
                redis_key = build_redis_key(event_code, dimension,
                                            menu_type)
                if redis_key:
                    redis_client.sadd(redis_key, value)

            except Exception:
                error_datas.append(value)

        return error_datas


class MenuFilterForm(BaseFilterForm):
    filter_event_code = forms.ChoiceField(label=_(u"项目类型"), required=False)
    filter_menu_type = forms.ChoiceField(label=_(u"名单类型"),
                                  choices=MENU_TYPE_CHOICES,
                                  required=False)
    filter_value = forms.CharField(label=_(u"值"), required=False)
    filter_menu_status = forms.ChoiceField(choices=MENU_STATUS_CHOICES,
                                    required=False)

    def __init__(self, *args, **kwargs):
        self.dimension = kwargs.pop("dimension", None)
        super(MenuFilterForm, self).__init__(*args, **kwargs)
        self.fields['filter_event_code'].choices = self._build_event_choices()

        placeholder = DIMENSION_NAME_MAP.get(self.dimension, u'未知')
        self.fields['filter_value'].widget.attrs["placeholder"] = _(
            placeholder)

    @classmethod
    def _build_event_choices(cls):
        db = get_mongo_client()
        choices = [(x["event_code"], x["event_name"]) for x in
                   db['menu_event'].find({}, projection={'_id': False,
                                                         'event_code': True,
                                                         'event_name': True})]
        choices.insert(0, ('', u"全部项目"))
        return choices

www/menu/views.py
# coding=utf8
from datetime import datetime
from collections import defaultdict

import pymongo
from bson import ObjectId
from django.views.generic import View
from braces.views import JSONResponseMixin
from django.core.urlresolvers import reverse

from core.generic import ListView
from core.utils import errors_to_dict
from core.pymongo_client import get_mongo_client
from core.redis_client import get_redis_client
from risk_models.menu import build_redis_key
from menu.forms import MenuCreateForm, MenuEventCreateForm, MenuFilterForm
from menu.tables import (
    EventTable, UseridTable, IPTable, UidTable, PayTable, PhoneTable
)


class EventListView(ListView):
    template_name = "menu/event_list.html"
    table_class = EventTable
    enable_page_size_config = True
    collection_name = "menu_event"

    def get_filter_form(self):
        return None

    def get_queryset(self):
        db = get_mongo_client()
        qs = db[self.collection_name].find()
        return qs

    def get_qs_count(self):
        db = get_mongo_client()
        count = db[self.collection_name].count()
        return count


class EventCreateView(JSONResponseMixin, View):
    def post(self, request, *args):
        form = MenuEventCreateForm(data=request.POST, request=request)
        if form.is_valid():
            event_code = form.save()
            data = dict(
                event_code=event_code,
                state=True,
                msg="ok"
            )
        else:
            data = dict(
                state=False,
                error=errors_to_dict(form.errors)
            )
        return self.render_json_response(data)


class EventDestroyView(JSONResponseMixin, View):
    def _check_event(self, event_code):
        """check名单项目是否被名单策略原子引用"""
        client = get_redis_client()
        for r in client.scan_iter(match="strategy_menu:*"):
            event_id = client.hget(r, 'event')
            if event_code == event_id:
                return True
        return False

    def post(self, request, *args, **kwargs):
        db = get_mongo_client()
        event_code = request.POST.get('id', '')
        res = db.menu_event.find_one({'event_code': event_code})
        if not res:
            return self.render_json_response(dict(
                state=False,
                error="not found"
            ))

        # 1 确保没有被名单管理使用
        if db.menus.find_one({"event": event_code}):
            return self.render_json_response(dict(
                state=False,
                error=u"已生成名单，无法删除"
            ))

        # 2 确保没有被名单策略使用
        is_using = self._check_event(event_code)
        if is_using:
            return self.render_json_response(dict(
                state=False,
                error=u"已生成名单策略原子，无法删除"
            ))

        db.menu_event.delete_one({'event_code': event_code})

        return self.render_json_response(dict(
            state=True,
            msg=u"ok"
        ))


class BaseMenuListView(ListView):
    enable_page_size_config = True
    collection_name = "menus"
    filter_form = MenuFilterForm
    extra_filter_kwargs = {}

    def build_filter_query(self):
        form_obj = self.filter_form(data=self.request.GET)
        if not form_obj.is_valid():
            return self.extra_filter_kwargs

        data = form_obj.cleaned_data
        value = data['filter_value']
        menu_type = data['filter_menu_type']
        event_code = data['filter_event_code']
        menu_status = data['filter_menu_status']
        query = {}
        if value:
            query['value'] = {'$regex': value}
        if menu_type:
            query['menu_type'] = menu_type
        if event_code:
            query['event_code'] = event_code
        if not menu_status:
            menu_status = u'有效'
        if menu_status != u'全部':
            query['menu_status'] = menu_status
        query.update(self.extra_filter_kwargs)
        return query

    def get_queryset(self):
        db = get_mongo_client()
        qs = db[self.collection_name].find(
            self.build_filter_query(),
            sort=[("create_time", pymongo.DESCENDING)]
        )
        return qs

    def get_qs_count(self):
        db = get_mongo_client()
        count = db[self.collection_name].find(
            self.build_filter_query()).count()
        return count

    def get_filter_form(self):
        return self.filter_form(data=self.request.GET,
                                dimension=self.extra_filter_kwargs.get("dimension"))

    def get_context_data(self, **kwargs):
        context = super(BaseMenuListView, self).get_context_data(**kwargs)
        context["create_form"] = MenuCreateForm()
        context["batch_delete_uri"] = reverse("menus:delete")
        return context


class MenuCreateView(JSONResponseMixin, View):
    def post(self, request, *args):
        form = MenuCreateForm(data=request.POST, request=request)
        if form.is_valid():
            error_datas = form.save()
            if error_datas:
                data = dict(
                    state=False,
                    error={"value": [u"以下数据添加失败:{0}".format(error_datas)]}
                )
            else:
                data = dict(
                    state=True,
                    msg="ok"
                )
        else:
            data = dict(
                state=False,
                error=errors_to_dict(form.errors)
            )
        return self.render_json_response(data)


class MenuDestroyView(JSONResponseMixin, View):
    def post(self, request, *args, **kwargs):
        db = get_mongo_client()
        ids = request.POST.get('ids')
        try:
            assert ids
            obj_ids = [ObjectId(id_) for id_ in ids.split(',')]
        except Exception:
            return self.render_json_response(dict(
                state=False,
                error=u"id不合法"
            ))

        redis_values_should_remove = defaultdict(list)

        menus_records = list(
            db['menus'].find({'_id': {"$in": obj_ids}, 'menu_status': u'有效'},
                             {'event_code': True, '_id': False,
                              'dimension': True,
                              'menu_type': True, 'value': True,
                              }))

        if not menus_records:
            return self.render_json_response(dict(
                state=False,
                error=u"记录均不存在"
            ))

        for d in menus_records:
            redis_key = build_redis_key(d['event_code'], d['dimension'],
                                        d['menu_type'])
            if redis_key:
                redis_values_should_remove[redis_key].append(d['value'])

        update_payload = {
            'menu_status': u'无效',
            'creator': request.user.username,
            'create_time': datetime.now(),
        }
        try:
            db.menus.update_many({'_id': {"$in": obj_ids}},
                                 {"$set": update_payload})

            #  同时删除redis中数据
            redis_client = get_redis_client()
            # todo pipeline
            for key, values in redis_values_should_remove.items():
                redis_client.srem(key, *values)
        except Exception:
            return self.render_json_response(dict(
                state=False,
                error=u"操作失败，请稍后重试"
            ))
        return self.render_json_response(dict(
            state=True,
            msg="ok"
        ))


class UseridListView(BaseMenuListView):
    template_name = "menu/userid_list.html"
    table_class = UseridTable
    extra_filter_kwargs = {"dimension": "user_id"}


class IpListView(BaseMenuListView):
    template_name = "menu/ip_list.html"
    table_class = IPTable
    extra_filter_kwargs = {"dimension": "ip"}


class UidListView(BaseMenuListView):
    template_name = "menu/uid_list.html"
    table_class = UidTable
    extra_filter_kwargs = {"dimension": "uid"}


class PayListView(BaseMenuListView):
    template_name = "menu/pay_list.html"
    table_class = PayTable
    extra_filter_kwargs = {"dimension": "pay"}


class PhoneListView(BaseMenuListView):
    template_name = "menu/phone_list.html"
    table_class = PhoneTable
    extra_filter_kwargs = {"dimension": "phone"}

www/menu/templates/menu/event_list.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block header %}
    <a href="javascript:;" class="active">名单项目管理</a>
{% endblock %}


{% block action %}
    <a class="roll-nav roll-right extra-right-btns pull-right" data-toggle="modal" data-target="#setEvent">
        <i class="fa fa-plus"></i>
        新增
    </a>
{% endblock %}


{% block main %}
    <div class="wrapper wrapper-content">
        <div class="extra-box-content">
            {% render_table table "table.html" %}
        </div>
    </div>


    <div class="modal inmodal fade" id="setEvent" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    新增名单项目
                </div>
                <div class="modal-body">
                    <input class="form-control" id="id_event_name" type="text" name="event_name" placeholder="项目名称">
                    <span id="id-event_name-error" class="help-block" style="color:darkred"></span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                    <button type="button" id="eventSave" class="btn btn-primary" data-uri="{% url 'menus:event_create' %}">保存</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
{{ block.super }}
{% include "datepicker.html" %}
{% include "menu/batch_delete.html" %}
<script>
    $(function () {
    // 删除
    $('.event-destroy').click(function () {
        var _this = $(this),
            uri = _this.data('uri'),
            id = _this.data('id');
        swal({
            title: "您确定要删除吗",
            type: "warning",
            allowOutsideClick: true,
            showCancelButton: true,
            confirmButtonColor: "#ff6700",
            confirmButtonText: "删除",
            cancelButtonText: "取消",
            closeOnConfirm: false
        }, function () {
            $.ajax({
                url: uri,
                data: {
                    'id': id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: "json",
                type: "POST",
                success: function (resp) {
                    if (resp.state) {
                        window.location.reload();
                    } else {

                        swal({
                            title: resp.error,
                            type: "error",
                            confirmButtonColor:"#ff6700"
                        });
                    }
                },
                error: function (err) {
                    if (err.statusText !== 'abort') {
                        swal({
                            title: "删除失败",
                            type: "error",
                            confirmButtonColor:"#ff6700"
                        });
                    }
                }
            })
        });
    });
    // 新增
    $('#eventSave').click(function () {
        var _this = $(this);
        var uri = _this.data('uri'),
            event_name = $("#id_event_name").val();
        $.ajax({
            url: uri,
            data: {
                'event_name': event_name,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: "json",
            type: "POST",
            success: function (resp) {
                if (resp.state) {
                    window.location.reload();
                } else {
                    var error = resp.error;
                    for (var name in error) {
                        $("#id-" + name +"-error").html(error[name][0]);
                    }
                }
            },
            error: function (err) {
                if (err.statusText !== 'abort') {
                    swal({
                        title: "哎呀，出错了",
                        type: "error",
                        confirmButtonColor:"#1ab394"
                    });
                }
            }
        })
    });
    // 错误提示复位
    $("#id_event_name").focus(function () {
        $("#id-event_name-error").html("");
    });
});
</script>
{% endblock %}

www/menu/templates/menu/pay_list.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block header %}
    <a href="javascript:;" class="active">支付账号管理</a>
{% endblock %}


{% block action %}
    <a class="roll-nav roll-right extra-right-btns pull-right" data-toggle="modal" data-target="#setValue">
        <i class="fa fa-plus"></i>
        新增
    </a>
{% endblock %}


{% block main %}
    <div class="wrapper wrapper-content">
        <div class="extra-search-form">
            {% crispy filter_form %}
        </div>
        <div class="extra-box-content">
            {% render_table table "table.html" %}
        </div>
    </div>


    <div class="modal inmodal fade" id="setValue" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
             <div class="modal-header">
                 <h2>新增支付账号名单</h2>
             </div>
             <div class="modal-body">
                 <textarea class="form-control" id="id_value" name="value" placeholder="支付账号[批量添加时请以回车键隔开]" rows="5"></textarea>
                 <span id="id-value-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 {{ create_form.menu_type }}
                 <span id="id-menu_type-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 {{ create_form.event_code }}
                 <span id="id-event_code-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 <input class="form-control datetime" id="id_end_time" name="end_time" placeholder="结束时间" type="datetime">
                 <span id="id-end_time-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 {{ create_form.menu_desc }}
                 <span id="id-menu_desc-error" class="help-block" style="color:darkred"></span>
             </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                  <button type="button" id="valueSave" class="btn btn-primary" data-uri="{% url 'menus:create' %}">保存</button>
              </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
{{ block.super }}
{% include "datepicker.html" %}
{% include "menu/batch_delete.html" %}
<script>
    $(function () {
        $('select#id_filter_event_code.form-control').searchableSelect();
        $('select#id_event_cod.form-control').searchableSelect();
    });
</script>
<script>
    $(function () {
    // 新增
    $("td.value").css("word-break", "break-all")
    $('#valueSave').click(function () {
        var _this = $(this);
        var uri = _this.data('uri'),
            value = $("#id_value").val(),
            menu_type = $("#id_menu_type").val(),
            event_code = $("#id_event_code").val(),
            end_time = $("#id_end_time").val(),
            menu_desc = $("#id_menu_desc").val();
        $.ajax({
            url: uri,
            data: {
                'value': value,
                'menu_type': menu_type,
                'event_code': event_code,
                'end_time': end_time,
                'menu_desc': menu_desc,
                'dimension': "pay",
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: "json",
            type: "POST",
            success: function (resp) {
                if (resp.state) {
                    window.location.reload();
                } else {
                    var error = resp.error;
                    for (var name in error) {
                        $("#id-" + name +"-error").html(error[name][0]);
                    }
                }
            },
            error: function (err) {
                if (err.statusText !== 'abort') {
                    swal({
                        title: "哎呀，出错了",
                        type: "error",
                        confirmButtonColor:"#1ab394"
                    });
                }
            }
        })
    });
    // 错误提示复位
    $("#id_value").focus(function () {
        $("#id-value-error").html("");
    });
    $("#id_menu_type").focus(function () {
        $("#id-menu_type-error").html("");
    });
    $("#id_event_code").focus(function () {
        $("#id-event_code-error").html("");
    });
    $("#id_start_time").focus(function () {
        $("#id-start_time-error").html("");
    });
    $("#id_end_time").focus(function () {
        $("#id-end_time-error").html("");
    });
    $("#id_menu_desc").focus(function () {
        $("#id-menu_desc-error").html("");
    });
});
</script>
{% endblock %}

www/menu/templates/menu/phone_list.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block header %}
    <a href="javascript:;" class="active">手机号管理</a>
{% endblock %}


{% block action %}
    <a class="roll-nav roll-right extra-right-btns pull-right" data-toggle="modal" data-target="#setValue">
        <i class="fa fa-plus"></i>
        新增
    </a>
{% endblock %}


{% block main %}
    <div class="wrapper wrapper-content">
        <div class="extra-search-form">
            {% crispy filter_form %}
        </div>
        <div class="extra-box-content">
            {% render_table table "table.html" %}
        </div>
    </div>


    <div class="modal inmodal fade" id="setValue" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
             <div class="modal-header">
                 <h2>新增手机号名单</h2>
             </div>
             <div class="modal-body">
                 <textarea class="form-control" id="id_value" name="value" placeholder="手机号[批量添加时请以回车键隔开]" rows="5"></textarea>
                 <span id="id-value-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 {{ create_form.menu_type }}
                 <span id="id-menu_type-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 {{ create_form.event_code }}
                 <span id="id-event_code-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 <input class="form-control datetime" id="id_end_time" name="end_time" placeholder="结束时间" type="datetime">
                 <span id="id-end_time-error" class="help-block" style="color:darkred"></span>
                 <div class="hr-line-dashed"></div>
                 {{ create_form.menu_desc }}
                 <span id="id-menu_desc-error" class="help-block" style="color:darkred"></span>
             </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                  <button type="button" id="valueSave" class="btn btn-primary" data-uri="{% url 'menus:create' %}">保存</button>
              </div>
            </div>
        </div>
    </div>

{% endblock %}


{% block js %}
{{ block.super }}
{% include "datepicker.html" %}
{% include "menu/batch_delete.html" %}
<script>
    $(function () {
        $('select#id_filter_event_code.form-control').searchableSelect();
        $('select#id_event_code.form-control').searchableSelect();
    });
</script>
<script>
    $(function () {
    // 新增
    $('#valueSave').click(function () {
        var _this = $(this);
        var uri = _this.data('uri'),
            value = $("#id_value").val(),
            menu_type = $("#id_menu_type").val(),
            event_code = $("#id_event_code").val(),
            end_time = $("#id_end_time").val(),
            menu_desc = $("#id_menu_desc").val();
        $.ajax({
            url: uri,
            data: {
                'value': value,
                'menu_type': menu_type,
                'event_code': event_code,
                'end_time': end_time,
                'menu_desc': menu_desc,
                'dimension': "phone",
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: "json",
            type: "POST",
            success: function (resp) {
                if (resp.state) {
                    window.location.reload();
                } else {
                    var error = resp.error;
                    for (var name in error) {
                        $("#id-" + name +"-error").html(error[name][0]);
                    }
                }
            },
            error: function (err) {
                if (err.statusText !== 'abort') {
                    swal({
                        title: "哎呀，出错了",
                        type: "error",
                        confirmButtonColor:"#1ab394"
                    });
                }
            }
        })
    });
    // 错误提示复位
    $("#id_value").focus(function () {
        $("#id-value-error").html("");
    });
    $("#id_menu_type").focus(function () {
        $("#id-menu_type-error").html("");
    });
    $("#id_event_code").focus(function () {
        $("#id-event_code-error").html("");
    });
    $("#id_start_time").focus(function () {
        $("#id-start_time-error").html("");
    });
    $("#id_end_time").focus(function () {
        $("#id-end_time-error").html("");
    });
    $("#id_menu_desc").focus(function () {
        $("#id-menu_desc-error").html("");
    });
});
</script>
{% endblock %}