www/rule/urls.py
# coding=utf8
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from rule.views import (RulesListView, RulesCreateView, RulesDestroyView, RulesChangeView,
                        RulesDetailView, RulesTestView, RulesDataView, RulesThresholdEdit,
                        RulesEdit)


urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy("rule:list"), permanent=True), name="rule_index"),
    url(r'^list/$', RulesListView.as_view(), name="list"),
    url(r'^create/$', RulesCreateView.as_view(), name="create"),
    url(r'^destroy/$', RulesDestroyView.as_view(), name="destroy"),
    url(r'^change/$', RulesChangeView.as_view(), name="change"),
    url(r'^detail/$', RulesDetailView.as_view(), name="detail"),
    url(r'^test/$', RulesTestView.as_view(), name="test"),
    url(r'^data/$', RulesDataView.as_view(), name="data"),
    url(r'^edit/$', RulesEdit.as_view(), name="edit"),
    url(r'^threshold_edit/$', RulesThresholdEdit.as_view(), name="threshold_edit"),
]

www/urls.py
# coding=utf8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include("risk_auth.urls", namespace='risk_auth')),
    url(r'permissions/', include("permissions.urls", namespace="permissions")),
    url(r'strategy/', include("strategy.urls", namespace="strategy")),
    url(r'menu/', include("menu.urls", namespace="menus")),
    url(r'rule/', include("rule.urls", namespace="rule")),
    url(r'config/', include("bk_config.urls", namespace="config")),
    url(r'log_manage/', include("log_manage.urls", namespace="log_manage")),
]

# 用于线上时应移除此部分，动静分离
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    from django.views.defaults import (page_not_found, server_error,
                                       permission_denied)

    urlpatterns += [
        url(r'404/', page_not_found),
        url(r'500/', server_error),
        url(r'403/', permission_denied),
    ]

www/rule/models.py
import json
import time
import uuid
from datetime import datetime

from django.conf import settings

from core.redis_client import get_redis_client
from risk_models.strategy import Strategys



class RuleModel(object):

    @classmethod
    def create(self, creator_name, title, describe, status, end_time,
               strategy_confs):
        strategy_obj = Strategys()

        new_strategy_confs = []
        for name, strategy_uuids, control, custom, weight in strategy_confs:
            strategy_uuids = strategy_uuids.split(';')

            new_strategy_confs.append({
                'name': name,
                'custom': custom,
                'control': control,
                'weight': weight,
                'strategy_list': [
                    [strategy_uuid,
                     strategy_obj.get_thresholds(strategy_uuid),
                     strategy_obj.get_strategy_name(strategy_uuid)] for
                    strategy_uuid in strategy_uuids]
            })

        strategy_list = sorted(new_strategy_confs,
                               key=lambda x: int(x["weight"]),
                               reverse=True)

        rule_uuid = str(uuid.uuid4())

        payload = {
            'uuid': rule_uuid,
            'user': creator_name,
            'update_time': str(int(time.time())),
            'end_time': datetime.strftime(end_time, '%Y-%m-%d %H:%M:%S'),
            'title': title,
            'describe': describe,
            'status': status,
            'strategys': json.dumps(strategy_list)
        }

        client = get_redis_client()
        rule_id = client.incr(settings.LAST_RULE_ID_KEY)
        payload['id'] = rule_id

        rule_key = 'rule:{}'.format(rule_uuid)
        client.hmset(rule_key, payload)
        return str(rule_id), rule_uuid

www/rule/forms.py
# coding=utf8
from __future__ import unicode_literals

import json

from django import forms
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from core.forms import BaseFilterForm, BaseForm
from risk_models.strategy import Strategys
from risk_models.rule import Rules
from rule.models import RuleModel

STATUS_CHOICES = (
    ('on', u"启用"),
    ('off', u"停用"),
)
CONTROL_CHOICES = (
    ('', u"管控原子选择"),
    ('pass', u"直接通过"),
    ('deny', u"拒绝"),
    ('log', u"记录日志"),
    ('message', u"短信验证"),
    ('picture', u"图片验证"),
    ('number', u"数字验证"),
    ('verify', u"审核"),
)
CONTROL_MAP = {
    k: v for k, v in CONTROL_CHOICES if k
}


class RulesForm(BaseForm):
    title = forms.CharField(label=_(u"规则名称"))
    describe = forms.CharField(required=False, label=_(u"规则描述"),
                               widget=forms.Textarea)
    status = forms.ChoiceField(label=_(u"状态"), choices=STATUS_CHOICES)
    end_time = forms.DateTimeField()
    strategy = forms.ChoiceField(label=_("策略原子"), required=False)
    control = forms.ChoiceField(label=_("管控原子"), choices=CONTROL_CHOICES,
                                required=False)
    custom = forms.CharField(label=_(u"客服话术"), required=False,
                             widget=forms.Textarea(
                                 attrs={'placeholder': u'客服话术',
                                        'data-autoresize': '',
                                        'rows': '1',
                                        'cols': 'auto'}))
    strategys = forms.CharField(required=True)
    controls = forms.CharField(required=True)
    customs = forms.CharField()
    names = forms.CharField(required=True)
    weights = forms.CharField(required=True)

    def __init__(self, *args, **kwargs):
        super(RulesForm, self).__init__(*args, **kwargs)
        strategy_choices = self._get_all_strategys()
        self.fields['strategy'].choices = strategy_choices
        self.strategy_names = strategy_choices

    @classmethod
    def _get_all_strategys(cls):
        return Strategys().get_all_strategy_uuid_and_name()

    def clean_end_time(self):
        end_time = self.cleaned_data['end_time']
        if end_time <= timezone.now():
            raise forms.ValidationError(_(u"结束时间应大于当前时间"))
        return end_time

    def clean_weights(self):
        weights = self.cleaned_data['weights']
        seps = weights.split(',')
        for num in seps:
            if not num.isdigit():
                raise forms.ValidationError(_(u"权重值不是数字"))
        return weights

    def _check_names(self, names, choices, sep=None):
        valid_names = set()
        for english, chinese in choices:
            if english:
                valid_names.add(english)
        if sep:
            all_names = []
            for name in names:
                for e in name.split(sep):
                    all_names.append(e)
            names = all_names
        return all([name in valid_names for name in names])

    def clean(self):
        cd = super(RulesForm, self).clean()

        # 已经有问题的话，就不继续校验了
        if self.errors:
            return cd

        strategys_list = cd['strategys'].split(',')
        controls = cd['controls'].split(',')
        customs = cd.get('customs', '').split(':::')
        names = cd['names'].split(':::')
        if not len(strategys_list) == len(controls) == len(customs) == len(
                names):
            self.errors['customs'] = [u'策略原子组名、策略原子、管控原子、客服话术不匹配']
        if not self._check_names(strategys_list, self._get_all_strategys(),
                                 sep=';'):
            self.errors['strategys'] = [u'非法策略原子名']
        if not self._check_names(controls, CONTROL_CHOICES):
            self.errors['controls'] = [u'非法管控原子名']
        strategy_uuids = []
        for strategy in strategys_list:
            item = strategy.split(';')
            item.sort()
            strategy_uuids.append("".join(item))
        if len(set(strategy_uuids)) < len(strategy_uuids):
            self.errors['strategys'] = [u'策略原子有重复']
        return cd

    def save(self, *args, **kwargs):
        cd = self.cleaned_data

        names = cd['names'].split(':::')
        controls = cd['controls'].split(',')
        strategys = cd['strategys'].split(',')
        customs = cd.get('customs', '').split(':::')
        weights = [int(x) for x in cd['weights'].split(',')]

        return RuleModel.create(creator_name=self.request.user.username,
                                title=cd['title'],
                                describe=cd['describe'], status=cd['status'],
                                end_time=cd['end_time'],
                                strategy_confs=zip(names, strategys, controls,
                                                   customs,
                                                   weights))


class RulesTestForm(BaseForm):
    req_body = forms.CharField(widget=forms.Textarea, label=_(u"请求体"))
    rule = forms.ChoiceField(label=_(u"规则名称"), widget=forms.Select())

    def __init__(self, *args, **kwargs):
        super(RulesTestForm, self).__init__(*args, **kwargs)
        self.fields['rule'].choices = self._build_rule_choices()

    @classmethod
    def _build_rule_choices(cls):
        return Rules().get_all_rule_uuid_and_name()

    def clean_req_body(self):
        req_body = self.cleaned_data.get('req_body', '')
        try:
            req_body = json.loads(req_body)
        except ValueError:
            raise forms.ValidationError(u"请求体不是合法json格式")
        return req_body


class RulesFilterForm(BaseFilterForm):
    status = forms.ChoiceField(label=_(u"状态"),
                               choices=(('', '所有状态'),) + STATUS_CHOICES,
                               required=False)
    rule_name = forms.CharField(label=_(u"规则名称(可模糊查询)"), required=False)

www/rule/templates/rule/rules_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}

<style>
    .err-msg {
        font-size: 10px; font-style:italic; color:red;
    }
</style>
    {{ form.media }}
{% endblock %}

{% block header %}
    <a href="javascript:;" class="active">规则详情</a>
{% endblock %}

{% block action %}
    <a id='id_edit_rule' class="roll-nav roll-right extra-right-btns pull-right">
        <i class="fa fa-cog"></i>
        编辑
    </a>
    <a class="roll-nav roll-right extra-right-btns pull-right" href="{% url 'rule:list' %}">
        <i class="fa fa-reply"></i>
        返回
    </a>
{% endblock %}


{% block main %}

    <div class="row">
        <div class="col-sm-12">
            <div class="extra-box-content p-xl" style="min-height: 400px;">
                <div class="row">
                    <div class="col-sm-6">
                        <address>
                            <strong>规则名称:</strong> {{ rule.title }}<br>
                            <strong>规则描述:</strong> {{ rule.describe }}<br>
                            <strong>规则状态:</strong> {% if rule.status == "on" %} 开启 {% else %} 关闭 {% endif %}<br>
                        </address>
                    </div>

                    <div class="col-sm-6">
                        <address>
                            <strong>规则ID:</strong> <label class="text-danger">{{ rule.id }}</label><br>
                            <strong>规则结束时间:</strong> <label class="text-danger">{{ rule.end_time }}</label><br>
                        </address>
                    </div>
                </div>

                <div class="table-responsive m-t">
                    <table class="table invoice-table" style="word-break:break-all; word-wrap:break-all;">
                        <thead>
                            <tr>
                                <th>策略原子组名称</th>
                                <th>权重</th>
                                <th>策略原子组列表</th>
                                <th>管控原子</th>
                                <th>客服话术</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for rule in rule.rule_list %}
                            <tr>
                                <td style="width: 10%">{{ rule.group_name }}</td>
                                <td style="width: 5%">{{ rule.weight }}</td>
                                <td style="width: 45%">
                                    <div><strong>{{ rule.strategy_name }}</strong></div>
                                </td>
                                <td style="width: 10%">{{ rule.control_display }}</td>
                                <td style="width: 20%">{{ rule.custom }}</td>
                                <td style="width: 10%">
                                    <a href="#" data-toggle="modal" data-target="#setThreshold"
                                       data-strategy_index = "{{ forloop.counter }}"
                                       data-strategy_list="{{ rule.strategy_list_str }}">编辑阈值</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="modal inmodal fade" id="setThreshold" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>修改阈值</h2>
                </div>
                <div class="modal-body">
                    <table class="table invoice-table">
                        <thead>
                            <tr>
                                <th style="width: 60%">策略原子</th>
                                <th style="width: 40%">阈值</th>
                            </tr>
                        </thead>
                        <tbody id="thresholdModalBody">
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
                    <button type="button" id="thresholdSave" class="btn btn-primary"
                            data-uri="{% url 'rule:threshold_edit' %}"
                            data-id="{{ rule.uuid }}">保存</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    {{ block.super }}

    <script>
    $("#setThreshold").on("show.bs.modal", function(e) {
        var strategyList = $(e.relatedTarget).data('strategy_list');  // 修改策略原子组的数据
        var strategyIndex = $(e.relatedTarget).data('strategy_index');  // 修改策略原子组的下标
        $("#thresholdModalBody").html("");
        $("#thresholdSave").attr('data-strategy_index', strategyIndex - 1);
        for (var i in strategyList) {
            // 构造 阈值input框
            var inputList = "";
            for (var t in strategyList[i][1]){
                if(t != 0){
                    inputList += '&nbsp;&nbsp;'
                }
                var inputItem = "<input style='width: 50px;' name='threshold_" + t +"' value='" +strategyList[i][1][t] +"'><span class='err-msg'></span>";
                inputList += inputItem
            }
            // 构造tr的html
            var htmlBody = "<tr><td><div class='strategy-item' data-uuid='"+ strategyList[i][0] +"'>" + strategyList[i][2] + "</div></td><td>" + inputList + "</td></tr>";
            $("#thresholdModalBody").append(htmlBody);
        }
    });

    $('#thresholdSave').click(function () {
        var _this = $(this);
        var hasError = false;
        var regexPattern = /^\d{1,10}(\.\d{1,2})?$/;
        var uri = _this.data('uri'),
            strategy_index = Number(_this.data('strategy_index')),
            rule_uuid = _this.data('id');
        var data = {'rule_uuid': rule_uuid, 'strategy_index':strategy_index, 'strategy_list': []};
        $(".strategy-item").each(function (index, obj) {
            var strategyUuid = $(this).data('uuid');
            var strategyDesc = $(this).html();
            var thresholdList =[];
            $(this).parents('tr').find("input").each(function () {
                var inputValue = $(this).val();
                // 验证input参数
                if (strategyDesc.match("^手机号")) {
                    var phoneRe = /^\d{1,4}(,\d{1,4})*$/;
                    if(phoneRe.test(inputValue)) {
                        $(this).next('span').html("");
                    } else {
                        $(this).next('span').html("参数不合法");
                        hasError = true
                    }
                }
                else if (strategyDesc.match("货币类型$")) {
                    if (inputValue.indexOf("，") !== -1){
                        $(this).next('span').html("参数不合法");
                        hasError = true;
                    } else {
                        $(this).next('span').html("");
                    }
                }
                else if(regexPattern.test(inputValue)) {
                        $(this).next('span').html("");
                } else {
                        $(this).next('span').html("参数不合法");
                        hasError = true
                }
                thresholdList.push(inputValue);
            });
            data["strategy_list"].push({'strategy_uuid':strategyUuid, 'threshold_list':thresholdList})
        });
        if(hasError){
            return false
        }
        $.ajax({
            url: uri,
            data: {
                "data":JSON.stringify(data),
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: "json",
            type: "POST",
            success: function (resp) {
                if (resp.state) {
                    window.location.reload();
                } else {
                    var error = resp.error;
                    swal({
                        title: "哎呀，出错了",
                        text: error,
                        type: "error",
                        confirmButtonColor:"#1ab394"
                    });
                }
            },
            error: function (err) {
                if (err.statusText !== 'abort') {
                    swal({
                        title: "哎呀，出错了",
                        type: "error",
                        confirmButtonColor:"#1ab394"
                    });
                }
            }
        })
    });
    </script>
    <script>
        var cur_url = window.location.href;
        var url = "{% url 'rule:edit'%}?"+cur_url.split("?")[1];
        $("#id_edit_rule").attr("href",url);
    </script>
{% endblock %}

www/rule/templates/rule/rules_list.html
{% extends 'base.html' %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block css %}
    {{ block.super }}
    <style>
        .action-button {
            margin-right: 20px;
        }
    </style>
{% endblock %}


{% block header %}
    <a href="javascript:;" class="active">规则配置</a>
{% endblock %}


{% block action %}
    <a class="roll-nav roll-right extra-right-btns pull-right" href="{% url 'rule:test' %}">
        <i class="fa fa-cog"></i>
        调试
    </a>
    <a class="roll-nav roll-right extra-right-btns pull-right" href="{% url 'rule:create' %}">
        <i class="fa fa-plus"></i>
        新增
    </a>
{% endblock %}


{% block main %}
    <div class="wrapper wrapper-content">
        <div class="extra-search-form">
            {% crispy filter_form %}
        </div>
        <div class="extra-box-content">
            {% render_table table "table.html" %}
        </div>
    </div>

    <div class="modal inmodal fade" id="show-detail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
             <div class="modal-header">
                 <h2>规则详情</h2>
             </div>
             <div class="modal-body">
                 <label class="form-control control-label" id="detail-title"></label>
                 <div class="hr-line-dashed"></div>
                 <label class="form-control control-label" id="detail-describe"></label>
                 <div class="hr-line-dashed"></div>
                 <label class="form-control control-label" id="detail-status"></label>
                 <div class="hr-line-dashed"></div>
                 <label class="form-control control-label" id="detail-end_time"></label>
                 <div class="hr-line-dashed"></div>
                 <ul id="detail-list">
                     <li style="display: none;">
                     </li>
                 </ul>
             </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-white" data-dismiss="modal">关闭</button>
              </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    {{ block.super }}

<script>
    $(function () {
    $('.rules-destroy').click(function () {
        var _this = $(this),
            uri = _this.data('uri'),
            id = _this.data('id');
        swal({
            title: "您确定要删除吗",
            type: "warning",
            allowOutsideClick: true,
            showCancelButton: true,
            confirmButtonColor: "#ff6700",
            confirmButtonText: "删除",
            cancelButtonText: "取消",
            closeOnConfirm: true
        }, function () {
            $.ajax({
                url: uri,
                data: {
                    'id': id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: "json",
                type: "POST",
                success: function (resp) {
                    if (resp.state) {
                        window.location.reload();
                    }
                },
                error: function (err) {
                    if (err.statusText !== 'abort') {
                        swal({
                            title: "删除失败",
                            type: "error",
                            confirmButtonColor:"#ff6700"
                        });
                    }
                }
            })
        });
    });
});
    $(function () {
    $('.rules-on').click(function () {
        var _this = $(this),
            uri = _this.data('uri'),
            title = _this.data('title'),
            status = _this.data('status'),
            id = _this.data('id');
        if(status === 'on'){
            swal({
                title: "规则" + title + "已启用",
                type: "error",
                confirmButtonColor:"#ff6700"
            });
            return;
        }
        swal({
            title: "您确定启用规则" + title + "吗?",
            type: "warning",
            allowOutsideClick: true,
            showCancelButton: true,
            confirmButtonColor: "#ff6700",
            confirmButtonText: "启用",
            cancelButtonText: "取消",
            closeOnConfirm: true
        }, function () {
            $.ajax({
                url: uri,
                data: {'id': id, 'status': status},
                dataType: "json",
                type: "POST",
                success: function (resp) {
                    if (resp.state) {
                        window.location.reload();
                    }
                },
                error: function (err) {
                    if (err.statusText !== 'abort') {
                        swal({
                            title: "启用失败",
                            type: "error",
                            confirmButtonColor:"#ff6700"
                        });
                    }
                }
            })
        });
    });
});

    $(function () {
    $('.rules-off').click(function () {
        var _this = $(this),
            uri = _this.data('uri'),
            title = _this.data('title'),
            status = _this.data('status'),
            id = _this.data('id');
        if(status === 'off'){
            swal({
                title: "规则" + title + "已停用",
                type: "error",
                confirmButtonColor:"#ff6700"
            });
            return;
        }
        swal({
            title: "您确定停用规则" + title + "吗?",
            type: "warning",
            allowOutsideClick: true,
            showCancelButton: true,
            confirmButtonColor: "#ff6700",
            confirmButtonText: "停用",
            cancelButtonText: "取消",
            closeOnConfirm: true
        }, function () {
            $.ajax({
                url: uri,
                data: {'id': id, 'status': status},
                dataType: "json",
                type: "POST",
                success: function (resp) {
                    if (resp.state) {
                        window.location.reload();
                    }
                },
                error: function (err) {
                    if (err.statusText !== 'abort') {
                        swal({
                            title: "停用失败",
                            type: "error",
                            confirmButtonColor:"#ff6700"
                        });
                    }
                }
            })
        });
    });
});

    $(function () {
    $('.rules-detail').click(function () {
        var _this = $(this),
            uri = _this.data('uri'),
            id = _this.data('id'),
            url = uri + "?id=" + id;
            window.location.href = url;
        });
    });

    $(function () {
    $('.rules-edit').click(function () {
        var _this = $(this),
            uri = _this.data('uri'),
            id = _this.data('id'),
            url = uri + "?id=" + id;
            window.location.href = url;
        });
    });

    $(function () {
        $('td .rules-on').map(function(){
            if($(this).attr("data-status") == "on"){
                $(this).parent().attr("hidden", "");
            }
        });
        $('td .rules-off').map(function(){
            if($(this).attr("data-status") == "off"){
                $(this).parent().attr("hidden", "");
            }
        });
    });

    $(function () {
        $('th.id').click(function () {
            var _this = $(this),
                new_uri = '';
            var uri = _this.find('a').attr('href');
            var target = window.location.href.substr(window.location.href.indexOf("?"));
            if(target.indexOf('sort=id') < 0){
                new_uri = uri.replace("sort=-id", "sort=id");
                _this.find('a').attr('href', new_uri);
            } else {
                new_uri = uri.replace("sort=id", "sort=-id");
                _this.find('a').attr('href', new_uri);
            }
        });
    })
</script>
{% endblock %}

www/rule/templates/rule/rules_test.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    {{ block.super }}


    {{ form.media }}
{% endblock %}

{% block header %}
    <a href="javascript:;" class="active">调试规则</a>
{% endblock %}

{% block action %}
    <a class="roll-nav roll-right extra-right-btns pull-right" href="{% url 'rule:list' %}">
        <i class="fa fa-reply"></i>
        返回
    </a>
{% endblock %}


{% block main %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-sm-12">
                <div class="ibox extra-float-margins">
                    <div class="extra-box-content">
                        <form method="post" class="form-horizontal" id="menu_create_form" action="{{ request.get_full_path }}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="col-sm-2 control-label">规则名称</label>
                                <div class="col-sm-9">
                                    {{ form.rule }}
                                    <span id="id-strategy-error" class="help-block" style="color:darkred"></span>
                                </div>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label">请求体</label>
                                <div class="col-sm-9">
                                    {{ form.req_body }}
                                    <span id="id-req_body-error" class="help-block" style="color:darkred"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-4 col-sm-offset-2">
                                     <button class="btn btn-primary" type="submit">测试</button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <div class="extra-box-content">
                        <div id="resultArea"></div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
{{ block.super }}


<script>
    $(function () {
    $("body").on("submit", '#menu_create_form', function (e) {
        $("#id-req_body-error").html("");
        $("#id-title-error").html("");
        $("#resultArea").html("");

        e.preventDefault();
        var form = $(this);
        var _this = $(this);
        var uri = _this.attr('action');
        var params = form.serializeArray();

        _this.addClass("posting");
        $.ajax({
            url: uri,
            data: params,
            dataType: "json",
            type: "POST",
            success: function (resp) {
                if (resp.state) {
                    var data = JSON.stringify(resp.data, null, 4);
                    $("#resultArea").html(data);
                } else {
                    _this.removeClass("posting");
                    var error = resp.error;
                    for (var name in error) {
                        $("#id-" + name +"-error").html(error[name][0]);
                    }
                }
            },
            error: function (err) {
                if (err.statusText !== 'abort') {
                    _this.removeClass("posting");
                    swal({
                        title: "哎呀，出错了",
                        type: "error",
                        confirmButtonColor:"#1ab394"
                    });
                }
            }
        })
    });
});

    function get_data_example() {
        var options=$("#id_rule option:selected");
        uuid = options.val();
        $.ajax({
            url: "{% url 'rule:data' %}",
            data: {
                "uuid":uuid,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            },
            dataType: "json",
            type: "POST",
            success: function(resp) {
                if (resp.state) {
                    var req_body = JSON.stringify(resp.req_body, null, 4);
                    $("#id_req_body").val(req_body);
                }
            },
        })
    }
</script>

<script>
    $(function () {
        $('select.form-control').searchableSelect();
    });
</script>
{% endblock %}