www/strategy/urls.py
# coding=utf8

from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from strategy.views import (
    BoolStrategyListView, BoolStrategyCreateView, BoolStrategyDestroyView,
    BoolStrategyTestView, BoolStrategyDataView,
    FreqStrategyListView, FreqStrategyCreateView, FreqStrategyDestroyView,
    FreqStrategyTestView, FreqStrategyDataView,
    MenuStrategyListView, MenuStrategyCreateView, MenuStrategyDestroyView,
    MenuStrategyTestView, MenuStrategyDataView,
    UserStrategyListView, UserStrategyCreateView, UserStrategyDestroyView,
    UserStrategyTestView, UserStrategyDataView,
)

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(url=reverse_lazy("strategy:strategy_list"),
                             permanent=True), name="strategy_index"),
    # 名单型策略
    url(r'^menu_strategy/list/$', MenuStrategyListView.as_view(),
        name="menu_strategy_list"),
    url(r'^menu_strategy/create/$', MenuStrategyCreateView.as_view(),
        name="menu_strategy_create"),
    url(r'^menu_strategy/destroy/$', MenuStrategyDestroyView.as_view(),
        name="menu_strategy_destroy"),
    url(r'^menu_strategy/test/$', MenuStrategyTestView.as_view(),
        name="menu_strategy_test"),
    url(r'^menu_strategy/data/$', MenuStrategyDataView.as_view(),
        name="menu_strategy_data"),

    # 布尔型策略
    url(r'^bool_strategy/list/$', BoolStrategyListView.as_view(),
        name="bool_strategy_list"),
    url(r'^bool_strategy/create/$', BoolStrategyCreateView.as_view(),
        name="bool_strategy_create"),
    url(r'^bool_strategy/destroy/$', BoolStrategyDestroyView.as_view(),
        name="bool_strategy_destroy"),
    url(r'^bool_strategy/test/$', BoolStrategyTestView.as_view(),
        name="bool_strategy_test"),
    url(r'^bool_strategy/data/$', BoolStrategyDataView.as_view(),
        name="bool_strategy_data"),

    # 时段频控策略
    url(r'^freq_strategy/list/$', FreqStrategyListView.as_view(),
        name="freq_strategy_list"),
    url(r'^freq_strategy/create/$', FreqStrategyCreateView.as_view(),
        name="freq_strategy_create"),
    url(r'^freq_strategy/destroy/$', FreqStrategyDestroyView.as_view(),
        name="freq_strategy_destroy"),
    url(r'^freq_strategy/test/$', FreqStrategyTestView.as_view(),
        name="freq_strategy_test"),
    url(r'^freq_strategy/data/$', FreqStrategyDataView.as_view(),
        name="freq_strategy_data"),

    # 限用户数型策略
    url(r'^user_strategy/list/$', UserStrategyListView.as_view(),
        name="user_strategy_list"),
    url(r'^user_strategy/create/$', UserStrategyCreateView.as_view(),
        name="user_strategy_create"),
    url(r'^user_strategy/destroy/$', UserStrategyDestroyView.as_view(),
        name="user_strategy_destroy"),
    url(r'^user_strategy/test/$', UserStrategyTestView.as_view(),
        name="user_strategy_test"),
    url(r'^user_strategy/data/$', UserStrategyDataView.as_view(),
        name="user_strategy_data"),
]

www/urls.py
# coding=utf8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

urlpatterns = [
    url(r'', include("risk_auth.urls", namespace='risk_auth')),
    url(r'permissions/', include("permissions.urls", namespace="permissions")),
    url(r'strategy/', include("strategy.urls", namespace="strategy")),
    url(r'menu/', include("menu.urls", namespace="menus")),
    url(r'rule/', include("rule.urls", namespace="rule")),
    url(r'config/', include("bk_config.urls", namespace="config")),
    url(r'log_manage/', include("log_manage.urls", namespace="log_manage")),
]

# 用于线上时应移除此部分，动静分离
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    from django.views.defaults import (page_not_found, server_error,
                                       permission_denied)

    urlpatterns += [
        url(r'404/', page_not_found),
        url(r'500/', server_error),
        url(r'403/', permission_denied),
    ]

www/strategy/forms.py
# coding=utf8
import copy
import uuid
import json

from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from builtin_funcs import BuiltInFuncs
from core.redis_client import get_redis_client
from core.forms import BaseForm, BaseFilterForm
from core.pymongo_client import get_mongo_client


OP_CHOICES = (
    ('is', u'是(使用、已经)'),
    ('is_not', u'不是(未使用、尚未)'),
    ('lt', u'小于...'),
    ('le', u'小于等于...'),
    ('eq', u'等于...'),
    ('ne', u'不等于...'),
    ('ge', u'大于等于...'),
    ('gt', u'大于...'),
)

FUNC_CHOICES = tuple(
    [(k, str(v)) for k, v in BuiltInFuncs.name_callable.items()]
)
VAR_CHOICES = (
    ('user_id', u'账号ID'),
    ('phone', u'手机号'),
    ('uid', u'当前设备ID'),
    ('ip', u'当前IP'),
    ('reg_ip', u'注册IP'),
    ('reg_uid', u'注册设备ID'),
)

DIM_CHOICES_MENU = (
    ('user_id', u'账号ID'),
    ('phone', u'手机号'),
    ('ip', u'当前IP'),
    ('reg_ip', u'注册IP'),
    ('uid', u'当前设备ID'),
    ('reg_uid', u'注册设备ID'),
)
OP_CHOICES_MENU = (
    ('is', u'在'),
    ('is_not', u'不在'),
)
TYPE_CHOICES_MENU = (
    (u'black', u'黑名单'),
    (u'white', u'白名单'),
    (u'gray', u'灰名单')
)

OP_MAP = dict(OP_CHOICES)
FUNC_MAP = dict(FUNC_CHOICES)
VAR_MAP = dict(VAR_CHOICES)
DIM_MAP_MENU = dict(DIM_CHOICES_MENU)
TYPE_MAP_MENU = dict(TYPE_CHOICES_MENU)
OP_MAP_MENU = dict(OP_CHOICES_MENU)


FREQ_STRATEGY_UNIQ_SET_KEYS = (
    'strategy_source', 'strategy_body', 'strategy_time', 'strategy_limit')
USER_STRATEGY_UNIQ_SET_KEYS = (
    'strategy_source', 'strategy_body', 'strategy_day', 'strategy_limit')


class BoolStrategyForm(BaseForm):
    strategy_name = forms.CharField(label=_(u"策略名称"))
    strategy_desc = forms.CharField(required=False, label=_(u"策略描述"))
    strategy_var = forms.ChoiceField(label=_(u"内置变量"), choices=VAR_CHOICES)
    strategy_op = forms.ChoiceField(label=_(u"操作码"), choices=OP_CHOICES)
    strategy_func = forms.ChoiceField(label=_(u"内置函数"), choices=FUNC_CHOICES)
    strategy_threshold = forms.CharField(label=_(u"阈值"), required=False)

    def __init__(self, *args, **kwargs):
        self.values_sign = None
        super(BoolStrategyForm, self).__init__(*args, **kwargs)

    def save(self):
        client = get_redis_client()
        uuid_ = str(uuid.uuid4())
        name = 'bool_strategy:{}'.format(uuid_)
        payload = {}
        for key in ('strategy_name', 'strategy_desc', 'strategy_var',
                    'strategy_op', 'strategy_func', 'strategy_threshold'):
            payload[key] = self.cleaned_data.get(key, '')
        payload['uuid'] = uuid_
        client.hmset(name, payload)
        client.sadd(settings.STRATEGY_SIGN_KEY, self.values_sign)
        return uuid_

    def is_exists(self, cleaned_data):
        client = get_redis_client()
        temp = copy.deepcopy(cleaned_data)
        temp.pop("strategy_desc", None)
        temp.pop("strategy_name", None)
        keys = sorted(temp.keys())
        values_sign = "".join([temp[x] for x in keys])
        exists = client.sismember(settings.STRATEGY_SIGN_KEY, values_sign)
        self.values_sign = values_sign
        if exists in (0, '0'):
            return False
        return True

    @staticmethod
    def _get_display_names(names):
        display_names = []
        for english_name, display_name in VAR_CHOICES:
            for name in names:
                if name == english_name:
                    display_names.append(display_name)
        return ','.join(display_names)

    def clean(self):
        cd = self.cleaned_data
        op_name = cd['strategy_op']
        threshold = cd['strategy_threshold']
        func_name = cd['strategy_func']
        var_name = cd['strategy_var']
        supported_ops = BuiltInFuncs.name_supported_ops[func_name]
        required_args = BuiltInFuncs.get_required_args(func_name)

        if self.is_exists(cd):
            self.errors['strategy_name'] = [u"该条记录已存在,请勿重复添加"]

        if var_name not in required_args:
            self.errors['strategy_var'] = [u'函数{}支持的内置变量为{}'.format(
                func_name,
                self._get_display_names(required_args)
            )]

        if op_name not in supported_ops:
            self.errors['strategy_op'] = [u'函数{}不支持此操作码'.format(func_name)]
        if op_name in ('is', 'is_not') and threshold:
            self.errors['strategy_op'] = [u'[{}]该操作码不接受阈值'.format(op_name)]

        if op_name in {'lt', 'le', 'eq', 'ne', 'ge', 'gt'}:
            if not threshold:
                self.errors['strategy_threshold'] = [
                    u'操作码{}必须包含阈值'.format(op_name)]
        return cd


class BoolStrategyTestForm(BaseForm):
    req_body = forms.CharField(widget=forms.Textarea, label=_(u"请求体"))
    strategy = forms.ChoiceField(label=_(u"策略"), widget=forms.Select())

    def __init__(self, *args, **kwargs):
        super(BoolStrategyTestForm, self).__init__(*args, **kwargs)
        self.fields['strategy'].choices = self._build_strategy_choices()

    @classmethod
    def _build_strategy_choices(cls):
        client = get_redis_client()
        choices = []
        for name in client.scan_iter(match="bool_strategy:*"):
            d = client.hgetall(name)
            if 'uuid' in d and 'strategy_name' in d:
                choices.append((d['uuid'], d['strategy_name']))
        choices.sort()
        return choices

    def clean_req_body(self):
        req_body = self.cleaned_data.get('req_body', '')
        try:
            req_body = json.loads(req_body)
        except ValueError:
            raise forms.ValidationError(u"请求体不是合法json格式")
        return req_body


class FreqStrategyTestForm(BoolStrategyTestForm):
    history_data = forms.CharField(widget=forms.Textarea, label=_(u"历史数据"),
                                   required=False)

    def clean_history_data(self):
        history_data = self.cleaned_data.get('history_data') or None
        if history_data:
            try:
                history_data = json.loads(history_data)
            except ValueError:
                raise forms.ValidationError(u"历史数据不是合法json格式")
        return history_data

    @classmethod
    def _build_strategy_choices(cls):
        client = get_redis_client()
        choices = []
        for name in client.scan_iter(match="freq_strategy:*"):
            d = client.hgetall(name)
            if 'uuid' in d and 'strategy_name' in d:
                choices.append((d['uuid'], d['strategy_name']))
        # choices.insert(0, ("", u"请选择策略名"))
        return choices


class FreqStrategyForm(BaseForm):
    strategy_name = forms.CharField(label=_(u"策略名称"))
    strategy_desc = forms.CharField(required=False, label=_(u"策略描述"))
    strategy_source = forms.CharField(label=_(u"数据源"))
    strategy_body = forms.CharField(label=_(u"主体名称"), required=True,
                                    help_text=u"例:同一账号同一IP地址抢红包限1次，勾选: 用户ID,当前IP")
    strategy_time = forms.CharField(label=_(u"时段(单位:秒)"),
                                    help_text=u"支持86400和24*60*60两种输入格式。")
    strategy_limit = forms.IntegerField(min_value=1, label=_(u"最大值"),
                                        initial=1)

    def __init__(self, *args, **kwargs):
        self.values_sign = None
        super(FreqStrategyForm, self).__init__(*args, **kwargs)

    def clean_strategy_time(self):
        strategy_time = self.cleaned_data.get("strategy_time", '')
        if "*" in strategy_time:
            args = strategy_time.split("*")
            try:
                for a in args:
                    assert int(a) > 0
                args = map(int, args)
                strategy_time = reduce(lambda x, y: x * y, args)
                assert strategy_time > 0
            except (ValueError, AssertionError):
                raise forms.ValidationError(u"参数不合法，仅支持正整数和*")
        else:
            try:
                strategy_time = int(strategy_time)
                assert strategy_time > 0
            except (ValueError, AssertionError):
                raise forms.ValidationError(u"参数不合法，仅支持正整数和*")
        return strategy_time

    def clean(self):
        client = get_redis_client()
        cd = self.cleaned_data
        source_key = cd['strategy_source']
        strategy_body_str = cd['strategy_body']
        valid_bodys = json.loads(client.hget('CONFIG_SOURCE_MAP', source_key))
        for strategy_body in strategy_body_str.split(','):
            if strategy_body not in valid_bodys:
                self.errors['strategy_body'] = [u"数据源没有{}。".format(strategy_body)]
                return

        fields = [str(cd.get(x, "")) for x in FREQ_STRATEGY_UNIQ_SET_KEYS]
        if not all(fields):
            return
        values_sign = ":".join(fields)
        if client.sismember(settings.STRATEGY_SIGN_KEY, values_sign):
            self.errors['strategy_name'] = [u"该条记录已存在,请勿重复添加"]
        self.values_sign = values_sign

    def save(self):
        client = get_redis_client()
        uuid_ = str(uuid.uuid4())
        name = 'freq_strategy:{}'.format(uuid_)
        payload = {}
        for key in ('strategy_name', 'strategy_desc', 'strategy_time',
                    'strategy_body', 'strategy_limit', 'strategy_source'):
            payload[key] = self.cleaned_data.get(key, '')
        payload['uuid'] = uuid_
        client.hmset(name, payload)
        client.sadd(settings.STRATEGY_SIGN_KEY, self.values_sign)
        return uuid_


class UserStrategyForm(BaseForm):
    strategy_name = forms.CharField(label=_(u"策略名称"))
    strategy_desc = forms.CharField(required=False, label=_(u"策略描述"))
    strategy_source = forms.CharField(label=_(u"数据源"))
    strategy_body = forms.CharField(label=_(u"主体名称"),
                                    help_text=u"例:同一设备当天仅限5个用户送礼加祝福值，勾选: 当前设备")
    strategy_day = forms.IntegerField(min_value=1, label=_(u"自然天数(单位：个)"),
                                      initial=1)
    strategy_limit = forms.IntegerField(min_value=1, label=_(u"限制用户数"),
                                        initial=1)

    def __init__(self, *args, **kwargs):

www/strategy/templates/strategy/bool_strategy_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
{{ block.super }}


{{ form.media }}
{% endblock %}


{% block header %}
<a href="javascript:;" class="active">新增布尔型策略</a>
{% endblock %}

{% block action %}
<a class="roll-nav roll-right extra-right-btns pull-right" href="{% url 'strategy:bool_strategy_list' %}">
    <i class="fa fa-reply"></i>
    返回
</a>
{% endblock %}


{% block main %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox extra-float-margins">
                <div class="extra-box-content">
                    <form method="post" class="form-horizontal" id="menu_create_form"
                          action="{{ request.get_full_path }}">
                        {% csrf_token %}

                        <!--<div class="hr-line-dashed"></div>-->
                        <div class="form-group">
                            <label class="col-sm-2 control-label">内置变量</label>
                            <div class="col-sm-10">
                                {{ form.strategy_var }}
                                <span id="id-strategy_var-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">操作码</label>
                            <div class="col-sm-10">
                                {{ form.strategy_op }}
                                <span id="id-strategy_op-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">内置函数</label>
                            <div class="col-sm-10">
                                {{ form.strategy_func }}
                                <span id="id-strategy_func-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">阈值</label>
                            <div class="col-sm-10">
                                {{ form.strategy_threshold }}
                                <span id="id-strategy_threshold-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">策略名称</label>
                            <div class="col-sm-10">
                                <input class="form-control" id="id_strategy_name" name="strategy_name" type="text">
                                <!--{{ form.strategy_name }}-->
                                <span id="id-strategy_name-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">策略描述</label>
                            <div class="col-sm-10">
                                {{ form.strategy_desc }}
                                <span id="id-strategy_desc-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
{{ block.super }}


<script>
    function makename(){
        var a = $("#id_strategy_var").find("option:selected").text();
        var b = $("#id_strategy_op").find("option:selected").text();
        var c = $(".searchable-select-item.selected")[0].innerHTML;
        var func_name = $("#id_strategy_func").find("option:selected").val();
        if(['is_proxy_ip', 'is_adsl_ip', 'is_cloud_ip', 'is_evil_ip', 'is_idc_ip'].indexOf(func_name) !== -1){
            $('#id-strategy_func-error').html("单独的ip信息并不能说明用户为恶意用户，请配合其他策略原子使用");
        } else {
            $('#id-strategy_func-error').html("");
        }
        if(b === c){
            c = "";
        }
        relation_ops = ["大于...","大于等于...","小于...","小于等于...","等于...","不等于..."]
        if(relation_ops.indexOf(b) === -1){
            $("#id_strategy_name").val(a + b + c);
        }else{
            $("#id_strategy_name").val(a + c + b);
        }
   }

    $('#id_strategy_var').on('change', makename);
    $('#id_strategy_op').on('change', makename);
    // $('#id_strategy_func').on('change', makename);  //加了搜索框插件,change 事件失效
    function replace_param(){
        var name = $("#id_strategy_name").val();
        var param = $("#id_strategy_threshold").val();
        var new_name = name.replace("...", param);
        $("#id_strategy_name").val(new_name);
    }
    $("#id_strategy_threshold").blur(replace_param);
</script>
<script>
    $(function () {
        // 创建漏洞表单提交
        $("body").on("submit", '#menu_create_form', function (e) {
            e.preventDefault();
            var form = $(this);
            var _this = $(this);
            var uri = _this.attr('action');
            var params = form.serializeArray();

            _this.addClass("posting");
            $.ajax({
                url: uri,
                data: params,
                dataType: "json",
                type: "POST",
                success: function (resp) {
                    if (resp.state) {
                        window.location.href = resp.redirect_url;
                    } else {
                        _this.removeClass("posting");
                        var error = resp.error;
                        for (var name in error) {
                            $("#id-" + name + "-error").html(error[name][0]);
                        }
                    }
                },
                error: function (err) {
                    if (err.statusText !== 'abort') {
                        _this.removeClass("posting");
                        swal({
                            title: "哎呀，出错了",
                            type: "error",
                            confirmButtonColor: "#1ab394"
                        });
                    }
                }
            })
        });
    });


    // 错误提示复位
    $("#id_strategy_op").focus(function () {
        $("#id-strategy_op-error").html("");
    });
    $("#id_strategy_threshold").focus(function () {
        $("#id-strategy_threshold-error").html("");
    });
    $("#id_strategy_var").focus(function () {
        $("#id-strategy_var-error").html("");
    });
    $("#id_strategy_func").focus(function () {
        $("#id-strategy_func-error").html("");
    });
</script>

<script>
    $(function () {
        $('select#id_strategy_func').searchableSelect();
    });
</script>


<script>
    //内置函数联动显示（需要特殊处理，因为加了搜索框插件）
    function get_data_example(){
        makename()
    }
</script>

<script>
    // typehead的宽度和同页面的input宽度一致
    function setWidth() {
        var input_element = document.getElementById("id_strategy_op");
        var objs = document.getElementsByClassName("searchable-select");
        for (var i = 0; i < objs.length; i++) {
            objs[i].style.cssText = "min-width:" + input_element.offsetWidth + "px;";
        }
    }

    window.onresize = setWidth;
    $(document).ready(setWidth)

</script>

{% endblock %}

www/strategy/templates/strategy/freq_strategy_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
{{ block.super }}



{{ form.media }}
{% endblock %}


{% block header %}
<a href="javascript:;" class="active">新增时段频控型策略</a>
{% endblock %}

{% block action %}
<a class="roll-nav roll-right extra-right-btns pull-right" href="{% url 'strategy:freq_strategy_list' %}">
    <i class="fa fa-reply"></i>
    返回
</a>
{% endblock %}


{% block main %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="ibox extra-float-margins">
                <div class="extra-box-content">
                    <form method="post" class="form-horizontal" id="menu_create_form"
                          action="{{ request.get_full_path }}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">数据源</label>
                            <div class="col-sm-10">
                                <select class="form-control" id="id_strategy_source" name="strategy_source">
                                </select>
                                <span id="id-strategy_source-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label" id="label-strategy_body">主体名称</label>
                            <div class="col-sm-10">
                                <input type="hidden" name="strategy_body" id="id_strategy_body">
                                <span id="cb-strategy_body"></span>
                                <span class="help-block">{{ form.strategy_body.help_text }}</span>
                                <span id="id-strategy_body-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">时段(单位:秒)</label>
                            <div class="col-sm-10">
                                {{ form.strategy_time }}
                                <span class="help-block">{{ form.strategy_time.help_text }}</span>
                                <span id="id-strategy_time-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">最大值</label>
                            <div class="col-sm-10">
                                {{ form.strategy_limit }}
                                <span id="id-strategy_limit-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">策略名称</label>
                            <div class="col-sm-10">
                                {{ form.strategy_name }}
                                <span id="id-strategy_name-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">策略描述</label>
                            <div class="col-sm-10">
                                {{ form.strategy_desc }}
                                <span id="id-strategy_desc-error" class="help-block" style="color:darkred"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-2">
                                <button class="btn btn-primary" type="submit">保存</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block js %}
{{ block.super }}


<script>
    var fun_setVal = function () {
        var source = $("#id_strategy_source").find("option:selected").text()
        var body = $("#id_strategy_body").val();
        var elements = body.split(',');
        body = elements.join(',');
        var time = $("#id_strategy_time").val();
        var limit = $("#id_strategy_limit").val();
        var pattern = /^[1-9]\d*$/; //匹配非负整数
        if (pattern.test(limit)) {
            $("#id-strategy_limit-error").html("");
            $("#id_strategy_name").val("相同" + body + "，在最近" + time + "s内，限" + limit + "次(" + source + ")");
        } else {
            $("#id-strategy_limit-error").html("请输入大于等于1的正整数。");
        }
    };
    fun_setVal();
    $('#id_strategy_source').on('change', fun_setVal);
    $('#id_strategy_time').on('propertychange input', fun_setVal);
    $('#id_strategy_limit').on('propertychange input', fun_setVal);
</script>


<script>
    $(function () {
        // 创建漏洞表单提交
        $("body").on("submit", '#menu_create_form', function (e) {
            e.preventDefault();
            var form = $(this);
            var _this = $(this);
            var uri = _this.attr('action');
            var params = form.serializeArray();

            _this.addClass("posting");
            $.ajax({
                url: uri,
                data: params,
                dataType: "json",
                type: "POST",
                success: function (resp) {
                    if (resp.state) {
                        window.location.href = resp.redirect_url;
                    } else {
                        _this.removeClass("posting");
                        var error = resp.error;
                        for (var name in error) {
                            $("#id-" + name + "-error").html(error[name][0]);
                        }
                    }
                },
                error: function (err) {
                    if (err.statusText !== 'abort') {
                        _this.removeClass("posting");
                        swal({
                            title: "哎呀，出错了",
                            type: "error",
                            confirmButtonColor: "#1ab394"
                        });
                    }
                }
            })
        });
    });

    // 渲染 数据源数据
    $.ajax({
        url: "/config/source/ajax/",
        data: {},
        dataType: "json",
        type: "GET",
        success: function (resp) {
            $.each(resp.data, function (i, e) {
                $('#id_strategy_source').append($('<option>', {
                    value: e['name_key'],
                    text: e['name_show']
                }));
                var val = e['name_key'];
                $("#label-strategy_body").attr("data-" + val, JSON.stringify(e['content']));
                if(i === 0) {
                    refresh_checkbox(val);
                }
            });
            change_combox_style();
        }
    });
    function change_combox_style() {
        $('select#id_strategy_source.form-control').searchableSelect();
        function setWidth() {
            var input_element = document.getElementById("id_strategy_desc");
            var objs = document.getElementsByClassName("searchable-select");
            for (var i = 0; i < objs.length; i++) {
                objs[i].style.cssText = "min-width:" + input_element.offsetWidth + "px;";
            }
        }
        window.onresize = setWidth;
        $(document).ready(setWidth)
    }
    function refresh_checkbox(name) {
        name = name.toLowerCase()
        var source_data = $("#label-strategy_body").data(name);
        $("#cb-strategy_body").html("");
        $.each(source_data, function (k, v) {
            var innerHtml = '<span style="margin-right: 10px"><input type="checkbox" class="sb_check" style="margin-right: 3px" name="strategy_body_check" value='+ v['name'] +'>' + v['desc'] + '</span>';
            $("#cb-strategy_body").append(innerHtml);
        });
    }

    function get_data_example() {
        // 数据源选择联动
        var source_name = $(".searchable-select-item.selected").data('value');
        refresh_checkbox(source_name);
    }

    // 定义strategy_body
    $(document).on("click", 'input:checkbox', function() {
        var arrs=[];
        $('input:checked[name=strategy_body_check]').each(function(){
            arrs.push($(this).val());
        });
        var strategy_body = arrs.join(',');
        $("input[name=strategy_body]").val(strategy_body)
        fun_setVal()
});


    // 错误提示复位
    $("#id_strategy_limit").focus(function () {
        $("#id-strategy_limit-error").html("");
    });
    $("#id_strategy_time").focus(function () {
        $("#id-strategy_time-error").html("");
    });

</script>
{% endblock %}